<a href="https://colab.research.google.com/github/shawongis/WMASDS-10-Section-B-/blob/main/Assignment_2_Shawon_20231086.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### HOMEWORK [Pandas and NumPy Exercise for Data Analysis]

**Md. Islamul Haque Shawon**<br>
**Roll: 20231086**

### 1. NumPy Array Exercises


In [ ]:
import numpy as np

# How to create an empty and a full NumPy array?
empty_array = np.empty((3, 4))
full_array = np.full((3, 4),3)
print(empty_array)
print(full_array)

[[1.16244081e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.16073170e-311 4.47032019e-038 5.58888316e-091 2.49020437e+180]
 [2.81110101e-033 2.82833594e-056 3.99910963e+252 1.16246428e-311]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
import numpy as np

# Create a Numpy array filled with all zeros
zeros_array = np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

# Create a Numpy array filled with all zeros
zeros_array = np.ones((3,3))
print(zeros_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

#Combining a one and a two-dimensional NumPy Array  
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[7, 8, 9], [10,11,12]])

combined_array = np.concatenate([arr1, arr2])
print(combined_array)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

# Counts the number of non-zero values in the array
x = np.array([0, 2, 0, 4, 0, 6])
count = np.count_nonzero(x)
print(count)

3


## 2. NumPy Matrix Exercises

In [ ]:
import numpy as np
          
# Get the maximum value from given matrix
x = np.matrix('[64, 1; 12, 3]')
y = x.max()
print(y)

64


In [ ]:
import numpy as np
          
# Get the minimum value from given matrix
x = np.matrix('[64, 1; 12, 3]')
y = x.min()
print(y)

1


In [ ]:
import numpy as np

# Find the number of rows and columns of a given matrix using NumPy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

num_rows, num_cols = matrix.shape

print("Number of rows:", num_rows)
print("Number of columns:", num_cols)


Number of rows: 3
Number of columns: 3


In [ ]:
import numpy as np

# Adding and Subtracting Matrices in Python
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2

print("matrix sum: \n", matrix_sum)
print("Matrix subtracting: \n", matrix_diff)


matrix sum: 
 [[ 8 10 12]
 [14 16 18]]
Matrix subtracting: 
 [[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
import numpy as np

# Matrix Multiplication in NumPy
matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])

matrix2 = np.array([[10, 20, 30], 
                    [40, 50, 60], 
                    [70, 80, 90]])

multi_matrix = np.matmul(matrix1, matrix2)

print(multi_matrix)


[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [ ]:
import numpy as np

# Ways to add row/columns in numpy array
x = np.array([[1, 2],
            [4, 5]])

y = np.array([3, 6])

new_row = np.vstack((x, y))
new_colum = np.hstack((x, y.reshape(-1, 1)))

print(new_row) 
print(new_colum)



[[1 2]
 [4 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

# Get the eigen values of a matrix
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

eigenvalues = np.linalg.eig(matrix)
print(eigenvalues)


(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [ ]:
import numpy as np

# How to count the frequency of unique values in NumPy array?
array = np.array([1, 2, 3, 2, 1, 4, 5, 6, 7, 8])

unique_values, counts = np.unique(array, return_counts=True)

print(unique_values)
print(counts)


[1 2 3 4 5 6 7 8]
[2 2 1 1 1 1 1 1]


In [ ]:
import numpy as np

# How to inverse a matrix using NumPy
matrix = np.array([[1, 2],
                   [3, 4]])

inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)



[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np

# How to Calculate the determinant of a matrix using NumPy?
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

determinant = np.linalg.det(matrix)
print(determinant)

-9.51619735392994e-16


In [ ]:
import numpy as np

# Convert covariance matrix to correlation matrix using Python
covariance_matrix = np.array([[1, 2, 3], 
                              [4, 5, 6], 
                              [7, 8, 9]])

correlation_matrix = covariance_matrix / np.std(covariance_matrix, axis=0)
print(correlation_matrix)

[[0.40824829 0.81649658 1.22474487]
 [1.63299316 2.04124145 2.44948974]
 [2.85773803 3.26598632 3.67423461]]


### 3. NumPy Indexing Exercises

In [ ]:
import numpy as np

# Replace NumPy array elements that doesn’t satisfy the given condition
x = np.array([[45, 52, 10],
              [15, 50, 25]])
print("Given array:")
print(x)

print("\nReplace all elements of array which are greater than 30. to 5.25")
x[x > 30.] = 5

print("New array :\n")
print(x)

Given array:
[[45 52 10]
 [15 50 25]]

Replace all elements of array which are greater than 30. to 5.25
New array :

[[ 5  5 10]
 [15  5 25]]


In [ ]:
lst = [1, 2, 3, 4, 5]

# Return the indices of elements where the given condition is satisfied
condition = lambda x: x < 3

indices = []
for i, x in enumerate(lst):
    if condition(x):
        indices.append(i)

print(indices)

[0, 1]


In [ ]:
import numpy as np

# Replace negative value with zero in numpy array
x = np.array([-1, 2, -3, 4, -5])
x[x < 0] = 0

print(x)


[0 2 0 4 0]


In [ ]:
import numpy as np

# Replace NaN values with average of columns
x = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [np.nan, 8, 9]])

col_avg = np.nanmean(x, axis=0)
x = np.where(np.isnan(x), np.expand_dims(col_avg, axis=0), x)

print(x)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [2.5 8.  9. ]]


In [ ]:
import numpy as np

# How to get values of an NumPy array at certain index positions?
x = np.array([1, 2, 3, 4, 5])
indices = [0, 2, 4]
values = x[indices]
print(values)


[1 3 5]


In [ ]:
import numpy as np

# Find indices of elements equal to zero in a NumPy array
x = np.array([1, 0, 3, 0, 5, 0])
indices = np.argwhere(x == 0)
print(indices)

[[1]
 [3]
 [5]]


In [ ]:
import numpy as np

# How to access different rows of a multidimensional NumPy array?
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row_1 = arr[0]
row_2 = arr[1]
row_3 = arr[2]

print(row_1)
print(row_2)
print(row_3)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
import numpy as np

array = np.array([[1, 2, np.nan],
                  [3, 4, 5],
                  [6, 7, 8]])

x = np.isnan(array).any(axis=0)

new_array = array[:, ~ x]

print(new_array)

[[1. 2.]
 [3. 4.]
 [6. 7.]]


In [ ]:
import numpy as np

# Get row numbers of NumPy array having element larger than X
array = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

row_number = np.max(array)
print(row_number)


9


## 4. NumPy Sorting and Searching Exercises

In [ ]:
import numpy as np

#How to get the indices of the sorted array using NumPy in Python?
arr = np.array([9, 2, 7, 4, 5])
indices = np.sort(arr)
print(indices)

[2 4 5 7 9]


In [ ]:
import numpy as np

# Finding the k smallest values of a NumPy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
k = 3
smallest_values = array[np.argpartition(array, k)[:k]]
print(smallest_values)

[1 2 3]


In [ ]:
import numpy as np

# How to get the n-largest values of an array using NumPy?
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
k = 3
largest_values = array[np.argpartition(array, -k)[-k:]]
print(largest_values)

[ 8  9 10]


In [ ]:
import numpy as np

# Sort the values in a matrix
matrix = np.array([[9, 2, 7],
                   [4, 5, 6],
                   [3, 1, 8]])

sorted_matrix = np.sort(matrix)
print(sorted_matrix)

[[2 7 9]
 [4 5 6]
 [1 3 8]]


In [ ]:
import numpy as np

# Filter out integers from float numpy array
array = np.array([1.0, 2.0, 3, 4.0, 5.0, 6, 7, 8, 9, 10])
filtered_array = array[np.isreal(array)]
print(filtered_array)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
import numpy as np

# Find the indices into a sorted array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices = np.argsort(array)
print(indices)

[0 1 2 3 4 5 6 7 8 9]


## 5. NumPy Random Exercises

In [ ]:
import numpy as np

# Create a Numpy array with random values
x = np.random.rand(3,3)
print(x)

[[0.75169336 0.35405791 0.51970811]
 [0.7895976  0.10215143 0.16669521]
 [0.73359322 0.28728156 0.55345945]]


In [ ]:
import numpy as np

# Generate Random Numbers From The Uniform Distribution using NumPy
random_number = np.random.uniform()
print(random_number)

0.5599753744161283


In [ ]:
import numpy as np

# Return a Matrix of random values from a uniform distribution
random_matrix = np.random.uniform(low=0, high=1, size=(3, 3))
print(random_matrix)

[[0.5889301  0.22470067 0.02502747]
 [0.31281432 0.65164123 0.29959241]
 [0.78264205 0.60227353 0.53540158]]


In [ ]:
import numpy as np

# Return a Matrix of random values from a Gaussian distribution
random_matrix = np.random.normal(loc=0, scale=1, size=(3, 3))
print(random_matrix)

[[-0.04898541 -0.92953797 -2.06191986]
 [ 1.86168069  0.78795185  0.3848955 ]
 [ 0.42346472 -0.3910173   1.30302498]]


## 6. Pandas Dataframe Exercises

In [ ]:
import pandas as pd

#Make a Pandas DataFrame with two-dimensional list
#Creating DataFrame from dict of narray/lists
data = [[5, 7, 3],
        [4, 5, 6],
        [7, 8, 9]]

col_nam = ['A', 'B', 'C']
row_nam = ['1', '2', '3']
x = pd.DataFrame(data, columns=col_nam, index=row_nam)

print(x)

   A  B  C
1  5  7  3
2  4  5  6
3  7  8  9


In [ ]:
import pandas as pd

#Creating Pandas dataframe using list of lists
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Height': [165, 175, 180]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Height
0    Alice   25     165
1      Bob   30     175
2  Charlie   35     180


In [ ]:
import pandas as pd

# Creating a Pandas dataframe using list of tuples
list_of_tuples = [(1, 2, 3), (4, 5, 6)]
df = pd.DataFrame(list_of_tuples, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6


In [ ]:
import pandas as pd

# Create a Pandas DataFrame from List of Dicts
list_of_dicts = [{'A': 1, 'B': 2, 'C': 3}, {'A': 4, 'B': 5, 'C': 6}]
df = pd.DataFrame(list_of_dicts)

print(df)


   A  B  C
0  1  2  3
1  4  5  6


In [ ]:
import pandas as pd

# Creating a dataframe from Pandas series
series = pd.Series([10, 20, 30, 40, 50])
x = pd.DataFrame(series, columns=['Values'])

print(x)

   Values
0      10
1      20
2      30
3      40
4      50


In [ ]:
import pandas as pd

# Reindexing in Pandas DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['X', 'Y', 'Z'])
print("Original DataFrame:")
print(df)

Original DataFrame:
   A  B
X  1  4
Y  2  5
Z  3  6


In [ ]:
import pandas as pd

# Reset Index in Pandas Dataframe
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df = df.reset_index()

print(df)

   index  A  B
0      0  1  4
1      1  2  5
2      2  3  6


In [ ]:
import pandas as pd

# Change column names and row indexes in Pandas DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['X', 'Y', 'Z'])
print("Original DataFrame:")
print(df)

new_column_names = {'A': 'Column1', 'B': 'Column2'}
df = df.rename(columns=new_column_names)
print("\nDataFrame with Changed Column Names:")
print(df)

Original DataFrame:
   A  B
X  1  4
Y  2  5
Z  3  6

DataFrame with Changed Column Names:
   Column1  Column2
X        1        4
Y        2        5
Z        3        6


## 7.    Pandas Dataframe Row Exercises

In [ ]:
# i) How to iterate over rows in Pandas Dataframe
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [25, 30, 22]}
df = pd.DataFrame(data)

for index, row in df.iterrows():
    print(index, row["Name"], row["Age"])
    
# ii) Different ways to iterate over rows in Pandas Dataframe
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [25, 30, 22]}
df = pd.DataFrame(data)

for i in range(len(df)):
    print(df.loc[i, "Name"], df.loc[i, "Age"])
    
# iii) Selecting rows in pandas DataFrame based on conditions
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [25, 30, 22]}
df = pd.DataFrame(data)

selected_rows = df[df['Age'] > 25]
print(selected_rows)

# iv) Select any row from a Dataframe using iloc[] and iat[] in Pandas
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [25, 30, 22]}
df = pd.DataFrame(data)

first_row = df.iloc[0]
print(first_row)

# v) Limited rows selection with given column in Pandas | Python
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [25, 30, 22]}
df = pd.DataFrame(data)

selected_rows = df[:2]
print(selected_rows)


# vi) Drop rows from the dataframe based on certain condition applied on a column
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

df = df.drop(df[df["Age"] > 30].index)
print(df)

# vii) Insert row at given position in Pandas Dataframe
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

new_row = {"Name": "Kalam", 'Age': 35}

insert_index = 1

df.loc[insert_index] = new_row

print(df)


# viii) Create a list from rows in Pandas dataframe
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

rows_list = df.values.tolist()

print(rows_list)

# ix) Ranking Rows of Pandas DataFrame
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

df["Rank"] = df["Age"].rank()
print(df)

# x) Sorting rows in pandas DataFrame
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

sorted_df = df.sort_values("Age", ascending=True)
print(sorted_df)

# xi) Select row with maximum and minimum value in Pandas dataframe
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

max_row = df.loc[df["Age"].idxmax()]

min_row = df.loc[df["Age"].idxmin()]

print("Row with maximum age:")
print(max_row)
print("\nRow with minimum age:")
print(min_row)

# xii) Get all rows in a Pandas DataFrame containing given substring
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

substring = 'i'
subset = df[df.astype(str).apply(lambda x: x.str.contains(substring)).any(axis=1)]

print(subset)

# xiii) Convert a column to row name/index in Pandas
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

df = df.set_index("Name")

print(df)


# xiv) How to randomly select rows from Pandas DataFrame
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal"],
        "Age": [35, 30, 22]}
df = pd.DataFrame(data)

random_rows = df.sample(n=2, replace=False)

print(random_rows)


0 Rahim 25
1 Karim 30
2 Jamal 22
Rahim 25
Karim 30
Jamal 22
    Name  Age
1  Karim   30
Name    Rahim
Age        25
Name: 0, dtype: object
    Name  Age
0  Rahim   25
1  Karim   30
    Name  Age
1  Karim   30
2  Jamal   22
    Name  Age
0  Rahim   35
1  Kalam   35
2  Jamal   22
[['Rahim', 35], ['Karim', 30], ['Jamal', 22]]
    Name  Age  Rank
0  Rahim   35   3.0
1  Karim   30   2.0
2  Jamal   22   1.0
    Name  Age
2  Jamal   22
1  Karim   30
0  Rahim   35
Row with maximum age:
Name    Rahim
Age        35
Name: 0, dtype: object

Row with minimum age:
Name    Jamal
Age        22
Name: 2, dtype: object
    Name  Age
0  Rahim   35
1  Karim   30
       Age
Name      
Rahim   35
Karim   30
Jamal   22
    Name  Age
1  Karim   30
2  Jamal   22


## 8.    Pandas Daraftame Columns Exercises

In [ ]:
# i) Create a pandas column using for loop
import pandas as pd

df = pd.DataFrame({"Name": ["Rahim", "Karim", "Jamal"]})

values = [1, 2, 3]

for i in range(len(values)):
    df["New_Column"] = values[i]

df["New_Column"] = df["New_Column"].astype(int)

# Print the DataFrame
print(df)


# ii) How to get column names in Pandas dataframe
import pandas as pd

data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}
df = pd.DataFrame(data)

column_names = df.columns
print(column_names)

column_names_array = df.columns.values
print(column_names_array)

# iii) How to rename columns in Pandas DataFrame
import pandas as pd

data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}
df = pd.DataFrame(data)

df = df.rename(columns={'A': 'Column1', 'B': 'Column2', 'C': 'Column3'})
print(df)

# iv) Get unique values from a column in Pandas DataFrame
import pandas as pd

data = {'Column1': [1, 2, 3, 2, 3, 4],
        'Column2': ['A', 'B', 'C', 'B', 'C', 'D']}
df = pd.DataFrame(data)

unique_values = df['Column1'].unique()
print(unique_values)

unique_values = df['Column2'].value_counts().index.tolist()
print(unique_values)

# v) Return the Index label if some condition is satisfied over a column in Pandas Dataframe
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)

max_score_index = df["Score"].idxmax()
print("Index label with maximum score:", max_score_index)

min_age_index = df["Age"].idxmin()
print("Index label with minimum age:", min_age_index)


# vi) Create a new column in Pandas DataFrame based on the existing columns
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)

df["NewColumn"] = df["Age"] + df["Score"]
print(df)


# vii) Creating a Pandas dataframe column based on a given condition
import pandas as pd
import numpy as np

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)

df["NewColumn"] = np.where(df["Score"] > 90, "High", "Low")
print(df)

# viii) Getting Unique values from a column in Pandas dataframe
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)
unique_names = df["Name"].unique()
print(unique_names)

# ix) Getting frequency counts of a columns in Pandas DataFrame
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)
name_counts = df["Name"].value_counts()
print(name_counts)

# x) Split a text column into two columns in Pandas DataFrame
import pandas as pd

data = {"Name": ["Mashiur Rahman", "Rakibul Islam", "Nazrul Islam"]}
df = pd.DataFrame(data)

df[['First Name', 'Last Name']] = df['Name'].str.split(pat=' ', n=1, expand=True)
print(df)


# xi) Get the index of minimum value in DataFrame column
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)

min_score_index = df["Score"].idxmin()
print("Index of minimum score:", min_score_index)

# xii) Get the index of maximum value in DataFrame column
data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)

max_score_index = df["Score"].idxmax()
print("Index of minimum score:", max_score_index)

# xiii) Difference of two columns in Pandas dataframe
import pandas as pd

data = {'A': [10, 20, 30, 40],
        'B': [5, 10, 15, 20]}
df = pd.DataFrame(data)

df['Difference'] = df['A'] - df['B']
print(df)

# xiv) Get n-largest values from a particular column in Pandas DataFrame
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)

n_largest_values = df["Score"].nlargest(2)
print(n_largest_values)

# xv) Get n-smallest values from a particular column in Pandas DataFrame
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)

n_smallest_values = df["Score"].nsmallest(2)
print(n_smallest_values)

# xvi) How to drop one or multiple columns in Pandas Dataframe
import pandas as pd

data = {"Name": ["Rahim", "Karim", "Jamal", "Kabir"],
        "Age": [25, 30, 22, 35],
        "Score": [85, 92, 88, 78]}
df = pd.DataFrame(data)
df = df.drop(columns="Score")
print(df)

    Name  New_Column
0  Rahim           3
1  Karim           3
2  Jamal           3
Index(['A', 'B', 'C'], dtype='object')
['A' 'B' 'C']
   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9
[1 2 3 4]
['B', 'C', 'A', 'D']
Index label with maximum score: 1
Index label with minimum age: 2
    Name  Age  Score  NewColumn
0  Rahim   25     85        110
1  Karim   30     92        122
2  Jamal   22     88        110
3  Kabir   35     78        113
    Name  Age  Score NewColumn
0  Rahim   25     85       Low
1  Karim   30     92      High
2  Jamal   22     88       Low
3  Kabir   35     78       Low
['Rahim' 'Karim' 'Jamal' 'Kabir']
Rahim    1
Karim    1
Jamal    1
Kabir    1
Name: Name, dtype: int64
             Name First Name Last Name
0  Mashiur Rahman    Mashiur    Rahman
1   Rakibul Islam    Rakibul     Islam
2    Nazrul Islam     Nazrul     Islam
Index of minimum score: 3
Index of minimum score: 1
    A   B  Difference
0 

## 9.    Pandas Series –  Practice Exercise

In [ ]:
# i) Create a Pandas Series from array
import pandas as pd
import numpy as np

array = np.array([1, 2, 3, 4, 5])
series = pd.Series(array)

print(series)

# ii) Creating a Pandas Series from Dictionary
import pandas as pd

data = {'A': 10, 'B': 20, 'C': 30, 'D': 40}

series = pd.Series(data)

print(series)

# iii) Creating a Pandas Series from Lists
import pandas as pd

labels = ['A', 'B', 'C', 'D']
values = [10, 20, 30, 40]

series = pd.Series(values, index=labels)

print(series)

# iv) Create Pandas Series using NumPy functions
import pandas as pd
import numpy as np

series = pd.Series(np.arange(10))

print(series)

# Access the elements of a Series in Pandas
import pandas as pd

series = pd.Series([10, 20, 30, 40, 50], index=['A', 'B', 'C', 'D', 'E'])

print(series['B'])  # Output: 20

print(series[['A', 'C', 'E']])  # Output: 

print(series[0])  # Output: 10
print(series[1:4])  # Output: 


0    1
1    2
2    3
3    4
4    5
dtype: int32
A    10
B    20
C    30
D    40
dtype: int64
A    10
B    20
C    30
D    40
dtype: int64
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32
20
A    10
C    30
E    50
dtype: int64
10
B    20
C    30
D    40
dtype: int64


## 10.   Pandas Datetime Exercises

In [ ]:
# Convert the column type from string to datetime format in Pandas dataframe
import pandas as pd

data = {'Date': ['2022-01-01', '2022-01-02', '2022-01-03']}
df = pd.DataFrame(data)

df['Date'] = pd.to_datetime(df['Date'])

print(df.dtypes)
print(df)


Date    datetime64[ns]
dtype: object
        Date
0 2022-01-01
1 2022-01-02
2 2022-01-03
